import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";
import type { ListingRecord } from "@motomoto/domain";
import { valueListing } from "@motomoto/valuation";

function listing(price:number, priceType:ListingRecord["priceType"]="FULL_PRICE", id=randomUUID()):ListingRecord{return {id,marketplace:"CAROUSELL",sourceListingId:id,originalUrl:`https://carousell.sg/p/${id}`,canonicalUrl:`https://carousell.sg/p/${id}`,listingStatus:"AVAILABLE",brand:"Suzuki",model:"GSR400",normalizedModel:"GSR400",engineCc:400,engineClass:"2A",askingPriceSgd:price,priceType,mileageKm:30000,registrationDate:"2020-01-01",ageYears:6,coeExpiry:"2030-01-01",coeRemainingYears:3.3,roadTaxExpiry:null,numberOfOwners:null,location:null,paymentOption:null,sellerType:"UNKNOWN",maintenanceSummary:null,accidentDisclosure:null,modifications:null,modificationImpact:"UNKNOWN",descriptionText:null,redFlags:[],conditionEvidence:[],conditionScore:null,conditionGroup:"COND-NA",capturedAt:"2026-08-01T00:00:00.000Z",firstSeenAt:"2026-08-01T00:00:00.000Z",lastSeenAt:"2026-08-01T00:00:00.000Z",extractionEvidence:[],dataQualityFlags:[],ingestionSource:"TEST",canonicalUrlHash:id,duplicateFingerprint:id,currentObservationId:randomUUID()};}
describe("deterministic valuation",()=>{
  it("uses independent full-price comparables and robust median",()=>{const target=listing(7000);const result=valueListing(target,[target,listing(6800),listing(7000),listing(7200),listing(50000)],new Date("2026-09-06"));expect(result.authoritativeComparableCount).toBe(4);expect(result.estimatedValueSgd).toBeGreaterThanOrEqual(6800);expect(result.estimatedValueSgd).toBeLessThanOrEqual(7200);});
  it("gates legacy unknown price evidence to low confidence",()=>{const target=listing(7000);const result=valueListing(target,[listing(6500,"UNKNOWN"),listing(6900,"UNKNOWN"),listing(7200,"UNKNOWN")],new Date("2026-09-06"));expect(result.confidence).toBe("LOW");expect(result.authoritativeComparableCount).toBe(0);expect(result.reasonCodes).toContain("LEGACY_UNKNOWN_PRICE_TYPES_ONLY");});
  it("returns insufficient when no comparable exists",()=>{const result=valueListing(listing(7000),[],new Date("2026-09-06"));expect(result.confidence).toBe("INSUFFICIENT");expect(result.estimatedValueSgd).toBeNull();});
  it("refuses a target whose price meaning is unverified",()=>{const result=valueListing(listing(7000,"UNKNOWN"),[listing(6800),listing(7200),listing(7000)],new Date("2026-09-06"));expect(result.confidence).toBe("INSUFFICIENT");expect(result.estimatedValueSgd).toBeNull();expect(result.reasonCodes).toContain("TARGET_PRICE_NOT_VERIFIED");});
});
