"use client";
import { useState } from "react";

type Item = { id:string; brand:string|null; model:string|null; askingPriceSgd:number|null; priceType:string; engineClass:string|null; mileageKm:number|null; coeRemainingYears:number|null; listingStatus:string; originalUrl:string };
type Response = { intent:{summary:string;source:string;hardFilters:Record<string,unknown>}; results:Item[]; total:number };
export default function SearchClient(){
  const [query,setQuery]=useState("Class 2A Japanese bike under S$8k for commuting"); const [data,setData]=useState<Response|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function search(){setLoading(true);setError("");try{const r=await fetch(`/api/v1/search?q=${encodeURIComponent(query)}`);if(!r.ok)throw new Error("Search failed");setData(await r.json());}catch(e){setError(e instanceof Error?e.message:"Search failed");}finally{setLoading(false)}}
  return <><div className="searchbox"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} aria-label="Search motorcycles"/><button className="button primary" onClick={search} disabled={loading}>{loading?"Searching…":"Search motorcycles"}</button></div>{error&&<div className="error">{error}</div>}{data&&<><div className="search-meta"><span className="pill">{data.total} available matches</span><span className="pill">Intent: {data.intent.source}</span>{Object.entries(data.intent.hardFilters).filter(([,v])=>v!==undefined).map(([k,v])=><span className="pill" key={k}>{k}: {String(v)}</span>)}</div>{data.results.length?<div className="results">{data.results.map(item=><a className="card" key={item.id} href={item.originalUrl.startsWith("http")?item.originalUrl:"#"} target="_blank" rel="noreferrer"><div className="status">{item.listingStatus}</div><h3>{item.brand} {item.model}</h3><div className="price">{item.askingPriceSgd?`S$${item.askingPriceSgd.toLocaleString()}`:"Price unknown"}</div><p>{item.engineClass?`Class ${item.engineClass}`:"Class unknown"} · {item.mileageKm?`${item.mileageKm.toLocaleString()} km`:"Mileage unknown"}<br/>{item.coeRemainingYears!==null?`${item.coeRemainingYears.toFixed(1)} years COE`:"COE unknown"}</p>{item.priceType==="UNKNOWN"&&<div className="warning">Price semantics unverified</div>}</a>)}</div>:<div className="empty">No current listings match those hard filters.</div>}</>}</>;
}
