type Marketplace="CAROUSELL"|"SGBIKEMART";
const capturedAt=()=>new Date().toISOString();
const market=():Marketplace=>location.hostname.includes("sgbikemart")?"SGBIKEMART":"CAROUSELL";
const clean=(value:string)=>value.replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,"[email removed]").replace(/(?:\+?65[\s-]?)?[689]\d{3}[\s-]?\d{4}\b/g,"[phone removed]").replace(/\s+/g," ").trim().slice(0,8000);
const num=(value:string|null)=>{const parsed=Number((value??"").replace(/[^\d.-]/g,""));return Number.isFinite(parsed)&&value?.trim()?parsed:null;};
const labels=()=>{const result=new Map<string,string>();document.querySelectorAll("tr").forEach(row=>{const cells=row.querySelectorAll("th,td");if(cells.length>1&&cells[0]?.textContent&&cells[1]?.textContent)result.set(cells[0].textContent.trim().toLowerCase(),cells[1].textContent.trim());});document.querySelectorAll("dt").forEach(dt=>{if(dt.textContent&&dt.nextElementSibling?.textContent)result.set(dt.textContent.trim().toLowerCase(),dt.nextElementSibling.textContent.trim());});return result;};
const pick=(map:Map<string,string>,...keys:string[])=>{for(const [key,value] of map)if(keys.some(test=>key.includes(test)))return value;return null;};
const iso=(value:string|null)=>{const m=value?.match(/(\d{1,2})[/-](\d{1,2})[/-](\d{4})/);return m?`${m[3]}-${m[2]?.padStart(2,"0")}-${m[1]?.padStart(2,"0")}`:null;};
function extract(){
  const map=labels();const title=(document.querySelector("h1")?.textContent||document.querySelector('meta[property="og:title"]')?.getAttribute("content")||document.title).trim();
  const brands=["Honda","Yamaha","Suzuki","Kawasaki","KTM","BMW","CFMoto","Royal Enfield","Triumph","Ducati","Vespa","Aprilia","SYM"];
  const brand=pick(map,"brand","make")||brands.find(item=>title.toLowerCase().includes(item.toLowerCase()))||null;
  const model=pick(map,"bike model","model")||(!brand?null:title.slice(title.toLowerCase().indexOf(brand.toLowerCase())+brand.length).split(/\s+(?:for sale|motorcycle|used|coe|\||-|,)/i)[0]?.trim()||null);
  const engineText=pick(map,"engine capacity","engine cc","capacity");const engineCc=num(engineText);const priceText=pick(map,"asking price","price")||document.querySelector('[itemprop="price"]')?.getAttribute("content")||document.querySelector('[class*="price" i]')?.textContent||"";
  const description=clean(document.querySelector('[data-testid*="description" i],[class*="description" i]')?.textContent||document.querySelector('meta[name="description"]')?.getAttribute("content")||"");
  const priceType=/\b(?:down\s*payment|deposit)\b/i.test(`${priceText} ${description}`)?"DOWNPAYMENT":/\b(?:per month|monthly instal(?:l)?ment|\/\s*mth)\b/i.test(`${priceText} ${description}`)?"MONTHLY_INSTALLMENT":/\b(?:total instal(?:l)?ment price)\b/i.test(`${priceText} ${description}`)?"TOTAL_INSTALLMENT_PRICE":/\b(?:full price|full cash|cash price|nett price)\b/i.test(`${priceText} ${description}`)?"FULL_PRICE":"UNKNOWN";
  const canonical=new URL(location.href);[...canonical.searchParams.keys()].filter(key=>key.startsWith("utm_")||["ref","source","share","tracking"].includes(key)).forEach(key=>canonical.searchParams.delete(key));canonical.hash="";
  const engineClass=(pick(map,"classification","engine class","class")?.match(/\b(2B|2A|2)\b/i)?.[1]?.toUpperCase()||(engineCc===null?null:engineCc<=200?"2B":engineCc<=400?"2A":"2"));
  const now=capturedAt();const evidence=(field:string,value:unknown,snippet:string|null,confidence=.94)=>value===null||value===""?[]:[{field,value,source:"MARKETPLACE_DOM",confidence,evidenceSnippet:snippet,userConfirmed:false,observedAt:now}];
  const coeExpiry=iso(pick(map,"coe expiry date","coe expiry","coe"));const registrationDate=iso(pick(map,"registration date","reg date","registration"));
  return {marketplace:market(),sourceListingId:location.pathname.match(/(?:-|\/)(\d{5,})(?:\/|$)/)?.[1]??null,originalUrl:location.href,canonicalUrl:canonical.toString().replace(/\/$/,""),listingStatus:/\bsold\b/i.test(document.body.textContent??"")?"SOLD":"AVAILABLE",brand,model,engineCc:engineCc===null?null:Math.round(engineCc),engineClass,askingPriceSgd:num(priceText),priceType,mileageKm:num(pick(map,"mileage")),registrationDate,ageYears:null,coeExpiry,coeRemainingYears:coeExpiry?Math.round((new Date(coeExpiry).valueOf()-Date.now())/(365.25*86400000)*100)/100:null,roadTaxExpiry:null,numberOfOwners:num(pick(map,"number of owners","owners")),location:pick(map,"location"),paymentOption:/\b(?:loan|finance|instal(?:l)?ment)\b/i.test(description)?"Financing mentioned":null,sellerType:/\bdirect seller\b/i.test(document.body.textContent??"")?"DIRECT_OWNER":/\b(?:dealer|company|pte ltd)\b/i.test(document.body.textContent??"")?"DEALER":"UNKNOWN",maintenanceSummary:null,accidentDisclosure:null,modifications:null,modificationImpact:/\b(?:stock|no modifications?)\b/i.test(description)?"STOCK_NONE":"UNKNOWN",descriptionText:description||null,redFlags:[],conditionEvidence:[],conditionScore:null,conditionGroup:"COND-NA",capturedAt:now,extractionEvidence:[...evidence("brand",brand,title),...evidence("model",model,title),...evidence("engineCc",engineCc,engineText),...evidence("askingPriceSgd",num(priceText),priceText),...evidence("priceType",priceType==="UNKNOWN"?null:priceType,priceText,.9)],dataQualityFlags:[],ingestionSource:"EXTENSION",extractorVersion:"motomoto-extension-v2.0.0",deterministicFieldCount:0};
}
chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type!=="MOTOMOTO_EXTRACT")return;try{const draft=extract();draft.deterministicFieldCount=draft.extractionEvidence.length;sendResponse({ok:true,draft});}catch(error){sendResponse({ok:false,error:error instanceof Error?error.message:"EXTRACTION_FAILED"});}});
