type Draft=Record<string,unknown>&{brand:string|null;model:string|null;askingPriceSgd:number|null;priceType:string;mileageKm:number|null;coeExpiry:string|null;marketplace:string;deterministicFieldCount:number};
const root=document.getElementById("root")!;let draft:Draft|null=null;let interpretation:any=null;
const backend=__MOTOMOTO_BACKEND__;
const shell=(content:string)=>`<main><header><img src="motomoto-logo.png" alt=""><div><strong>MotoMoto.ai</strong><small>Evidence-led bike intelligence</small></div></header>${content}</main>`;
const htmlEscape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));
function renderIntro(supported:boolean){root.innerHTML=shell(supported?`<section class="intro"><span class="tag">Supported marketplace</span><h1>Know what this bike is worth.</h1><p>Extract listing facts, review the evidence, and compare only when you choose.</p><button id="extract">Extract listing</button><small class="privacy">No database write occurs during extraction or interpretation.</small></section>`:`<section class="empty"><h2>Open a supported listing</h2><p>Visit an individual motorcycle listing on Carousell or SGBikeMart, then reopen this panel.</p></section>`);document.getElementById("extract")?.addEventListener("click",extractListing);}
function progress(title:string,text:string){root.innerHTML=shell(`<section class="progress"><div class="spinner"></div><h2>${title}</h2><p>${text}</p></section>`);}
function failure(message:string){root.innerHTML=shell(`<section class="empty"><h2>We couldn't continue</h2><p>${htmlEscape(message)}</p><button id="retry">Try again</button></section>`);document.getElementById("retry")?.addEventListener("click",()=>renderIntro(true));}
async function extractListing(){progress("Reading listing fields…","Only relevant listing facts and sanitized description text are processed.");try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw new Error("No active tab");const response=await chrome.tabs.sendMessage(tab.id,{type:"MOTOMOTO_EXTRACT"});if(!response?.ok)throw new Error(response?.error??"Extraction failed");draft=response.draft;progress("Interpreting evidence…","Deterministic evidence remains stronger than AI advice.");const result=await fetch(`${backend}/api/v1/interpret`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({draft})});if(!result.ok)throw new Error("Interpretation service unavailable");interpretation=await result.json();draft=interpretation.draft;renderReview();}catch(error){failure(error instanceof Error?error.message:"Unable to extract");}}
function renderReview(){if(!draft)return;root.innerHTML=shell(`<section><span class="tag">Review before analysis</span><h1>${htmlEscape(draft.brand)} ${htmlEscape(draft.model)}</h1><div class="source">${htmlEscape(draft.marketplace)} · ${draft.deterministicFieldCount} deterministic fields</div><div class="form"><label>Brand<input id="brand" value="${htmlEscape(draft.brand)}"><em>Marketplace evidence</em></label><label>Model<input id="model" value="${htmlEscape(draft.model)}"><em>Marketplace evidence</em></label><label>Asking price (SGD)<input id="price" type="number" value="${draft.askingPriceSgd??""}"></label><label>Price meaning<select id="priceType"><option value="UNKNOWN">Please confirm</option><option value="FULL_PRICE">Full cash / asking price</option><option value="TOTAL_INSTALLMENT_PRICE">Complete total instalment price</option><option value="DOWNPAYMENT">Downpayment only</option><option value="MONTHLY_INSTALLMENT">Monthly instalment only</option></select><em>This must be confirmed before a responsible valuation.</em></label><label>Mileage (km)<input id="mileage" type="number" value="${draft.mileageKm??""}"></label><label>COE expiry<input id="coe" type="date" value="${draft.coeExpiry??""}"></label></div><button id="analyse">Analyse this bike</button><p class="hint" id="hint"></p><p class="privacy">This click authorizes one listing observation to be stored.</p></section>`);(document.getElementById("priceType") as HTMLSelectElement).value=draft.priceType;document.getElementById("analyse")?.addEventListener("click",analyse);}
async function analyse(){if(!draft)return;draft.brand=(document.getElementById("brand") as HTMLInputElement).value||null;draft.model=(document.getElementById("model") as HTMLInputElement).value||null;draft.askingPriceSgd=Number((document.getElementById("price") as HTMLInputElement).value)||null;draft.priceType=(document.getElementById("priceType") as HTMLSelectElement).value;draft.mileageKm=Number((document.getElementById("mileage") as HTMLInputElement).value)||null;draft.coeExpiry=(document.getElementById("coe") as HTMLInputElement).value||null;if(!draft.brand||!draft.model||!draft.askingPriceSgd||!["FULL_PRICE","TOTAL_INSTALLMENT_PRICE"].includes(draft.priceType)){document.getElementById("hint")!.textContent="Confirm brand, model, asking price, and its full-price meaning to continue.";return;}progress("Saving and comparing…","Creating one stable listing observation, then running deterministic valuation.");try{const response=await fetch(`${backend}/api/v1/analyse`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reviewedDraft:draft,aiEvidence:interpretation?.aiEvidence??[],userOverrides:[]})});const result=await response.json();if(!response.ok)throw new Error(result.message??"Analysis failed");renderResult(result);}catch(error){failure(error instanceof Error?error.message:"Analysis failed");}}
function renderResult(result:any){const valuation=result.valuation;const money=(v:number|null)=>v?`S$${Math.round(v).toLocaleString()}`:"Not available";root.innerHTML=shell(`<section><span class="confidence ${(valuation?.confidence??"insufficient").toLowerCase()}">${htmlEscape(valuation?.confidence??"INSUFFICIENT")} confidence</span><h1>${valuation?.estimatedValueSgd?money(valuation.estimatedValueSgd):"Evidence captured"}</h1>${valuation?.rangeLowSgd?`<div class="range">Indicative range<strong>${money(valuation.rangeLowSgd)} – ${money(valuation.rangeHighSgd)}</strong></div>`:""}<p>${htmlEscape(result.message)}</p><div class="stats"><div><strong>${valuation?.authoritativeComparableCount??0}</strong><span>independent full-price comparables</span></div><div><strong>${Math.round((valuation?.confidenceScore??0)*100)}%</strong><span>confidence score</span></div></div>${valuation?.reasonCodes?.length?`<div class="notice">Limitations: ${htmlEscape(valuation.reasonCodes.join(" · "))}</div>`:""}<p class="privacy">${htmlEscape(valuation?.disclaimer??"")}</p><button class="ghost" id="again">Analyse another</button></section>`);document.getElementById("again")?.addEventListener("click",()=>renderIntro(true));}
chrome.tabs.query({active:true,currentWindow:true}).then(([tab])=>renderIntro(/(?:carousell\.sg|sgbikemart\.com\.sg)/i.test(tab?.url??"")));
